// returns the sum of the multiples of 3 or 5 up to
// but not including n
extern int sum3or5(int n);

// calculates the length of the sequence generated by a 3n + 1
// problem from a positive integer n
extern int sequence(int n);

// calculates the longest possible sequence generated by a
// 3n + 1 problem by any positive integer less than 1,000,001
extern int longest();

// displays a diamond with a middle row that contains n stars
// and a height that is also n rows high
extern void diamond(int n);

