#include <stdio.h>

extern int sum3or5(int n);
extern int sequence(int n);
extern int longest();
extern void diamond(int n);


int main() {

	int a, b, c = 0;

	printf("Please enter a positive integer: ");
	scanf("%d", &a);
	printf("The sum of all numbers that are multiples of 3 or 5 less than %d is %d\n", a, sum3or5(a));

	printf("Please enter a positive integer: ");
	scanf("%d", &b);
	printf("The length generated by %d is %d\n", b, sequence(b));
	printf("The longest length generated by a number less than 1 million is %d\n", longest());

	printf("Please enter a positive odd integer: ");
	scanf("%d", &c);

	while (c != -1) {
		diamond(c);
		printf("Please enter a positive odd integer: ");
		scanf("%d", &c);
	}

	printf("Bye!\n");
}
